### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by sileht** [talkiq/aredis#17]
Hi there, we plan to switch to 3.10 at @Mergifyio

Can we get a release with the recent python3.10 fixes ?

Best,
Mehdi

**Comment by sileht** [comment]
Anything I can do to help?

**Comment by sileht** [comment]
Still no release? Are this project alive?

**Comment by TheKevJames** [comment]
@sileht apologies, I've been out of office for a fairly extended period. I'll push a release shortly!

**Comment by TheKevJames** [comment]
v3.0.0 is now live with support for Python 3.10.

**Comment by sileht** [comment]
Thanks a lot!
