### ISSUE TITLE
Follow redis-py's api and auto check the differences between this and redis-py

### ISSUE THREAD

**Issue by synodriver** [talkiq/aredis#18]
It seems that [redis-py](https://github.com/Redis/redis-py)  is now maintained by redis's developers, whose version is 4.0 now.
From the beginning, we know that this project is ported from redis-py. 
>An efficient and user-friendly async redis client ported from redis-py (which is a Python interface to the Redis key-value)

So, how about keep following redis-py's api?

The following script can check the differences between this and redis-py, including methods' signatures, what methods are miss in yaaredis, and the response callbacks' differences.

```
import inspect

import redis
import yaaredis

def test_function():
    aredis = set(dir(yaaredis.StrictRedis))
    red = set(dir(redis.StrictRedis))

    # print(dir(aredis))
    # print('------')
    # print(dir(red))
    print("currently, yaaredis lack those methods")
    print(red - aredis)  # todo checkthis
    both = red & aredis

    print("\nbesides, those methods hava different signature, during this test, aredis's method can have more params")
    for func in both:
        try:
            redis_ins = inspect.signature(getattr(redis.StrictRedis, func))
            aredis_ins = inspect.signature(getattr(yaaredis.StrictRedis, func))

            for name, param in redis_ins.parameters.items():
                if name not in aredis_ins.parameters:
                    print(f"aredis.Redis.{func} not equal to redis-py, expect {redis_ins} got {aredis_ins}")
                    break

            # if str(redis_ins) != str(aredis_ins):
            #     print(f"{func} not equal，redis-py is{redis_ins} but aredis is {aredis_ins}")
        except TypeError:
            print(f"{func} is not callable, ignore")
        except ValueError:
            print(f"{func} is builtin, ignore")
    print('\ncheck response callbacks\n')
    # check response callbacks
    for cb, fn in redis.Redis.RESPONSE_CALLBACKS.items():

        if cb not in yaaredis.Redis.RESPONSE_CALLBACKS:
            print(f'aredis lack callback for {cb} command, whose function name is {fn}')

        else:
            try:
                if fn.__code__.co_code != yaaredis.Redis.RESPONSE_CALLBACKS[cb].__code__.co_code:
                    print(f"aredis's callback {cb} is different from redis-py's, expect {fn}, got {yaaredis.Redis.RESPONSE_CALLBACKS[cb]}, copy that from redis-py should be ok", flush=True)
            except AttributeError:   # class type
                if fn != yaaredis.Redis.RESPONSE_CALLBACKS[cb]:
                    print(f"aredis's callback {cb} is different from redis-py's, expect {fn}, got {yaaredis.Redis.RESPONSE_CALLBACKS[cb]}, copy that from redis-py should be ok", flush=True)

test_function()
```
This can be used as a reference for improvement.

It's a huge job to achieve this, but just give it a try? [Here](https://github.com/ProjectHentai/yaaredis) is my progress.

**Comment by synodriver** [comment]
By the way, I haven't finish it yet :)
Besides, some design of redis-py is not very good, for example, ```LMOVE```'s response callback, which is ```bool```, but according to the [doc](https://redis.io/commands/LMOVE), the return value is the element being popped and pushed, and how could it be bool? So I think some changes are necessary, so that auto-checking script is just a reference.

**Comment by TheKevJames** [comment]
I love the concept of this! Anything which could reduce the burden of maintenance would be fantastic -- it's certainly one of the annoying aspects of the redis ecosystem (in python, at least), where new packages have to be built for cluster support, or for async support, or... My ideal would be if yaaredis could act more like a wrapper around redis-py, eg. by adding on cluster/async capabilities without needing to replace things wholesale.

With respect to matching the API, it's a hard problem (as you've mentioned!). I think that second comment of yours outlines the complexity for me: on one hand, obeying their interface would make usage of this library as simple as possible. On the other hand, some of the suboptimal design decisions (such as the one you mentioned) are probably better fixed anyway.

What might actually be ideal would be to check our code against the redis docs pages, or the literal server implementation, or something along those lines! Not sure how possible that would be, of course.

**Comment by synodriver** [comment]
Check the existing code against the redis docs pages would be a huge work if do it manually, I'd prefer some auto-checking script like I mentioned above, or we could just open an issue in redis-py's repo and waiting for them to fix?

**Comment by TheKevJames** [comment]
Opening issues on redis-py's side definitely makes sense as well: if their return values are incorrect, I'm sure that's something they'd appreciate knowing and fixing!
