### ISSUE TITLE
cluster SCAN - provide a per node function to execute?

### ISSUE THREAD

**Issue by eoghanmurray** [talkiq/aredis#9]
In relation to #7 

I wonder would a good enhancement be to create a version of `scan_iter` that receives a callback function instead of a loop.

The callback function would have a signature `async def cb(node, key)`

This way you could execute commands on the key directly against the correct node, and also in parallel across nodes (but sequentially on a single node).

I think we'd need a better interface than `cx.execute_command_on_nodes([node]...` though for this to be comfortable (I don't even know if that's possible to call externally?)

Thoughts?
Would it need a different name from `scan_iter` or should it just accept a new `callback` parameter?

**Comment by TheKevJames** [comment]
Hmm, what's the use-case here? eg. what sort of commands would you envision wanting to provide via callback?

Initially, this sounds orthogonal to the `scan_iter` command entirely -- this sounds more like just providing a general way to "run arbitrary method on each node"?

**Comment by eoghanmurray** [comment]
Run an arbitrary method on each node against a particular key that lives on that node...

I've been running something like this for a while now in production and it has provided very good speedups.

Use cases:
 - find out the memory usage of each key that you are scanning
 - peek streams to determine whether they need further processing

These all benefit from the parallel execution of the follow-up command.  I dunno how much benefit is derived from executing the command directly against the correct cluster node, but I reckon it isn't hurting.
